### ISSUE TITLE
complaining about no pyqgis

### ISSUE THREAD

**Issue by lhirlimann** [3liz/qgis-plugin-manager#17]
```
root@VLIZ253F001:/srv/qgis/plugins# qgis-plugin-manager init
Cannot check version with PyQGIS, check your QGIS installation or your PYTHONPATH
QGIS version is unknown, creating with a default 3.16
```

I have fcgi qgis installed.

**Comment by lhirlimann** [comment]
Also
root@VLIZ253F001:/srv/qgis/plugins# python --version
Python 2.7.16

That might be the issue. But I did a pip3 install

**Comment by Gustry** [comment]
As written in the message :  

> Cannot check version with PyQGIS, check your QGIS installation or your PYTHONPATH

You must check the installation.

> python --version

On most OS, you should still do `python3 --version`. `python` is still an alias to `python2`, but on the the machine, you may have `python3.9`, `python3` binaries as well.
