### ISSUE TITLE
Upgrade argument invalid choice

### ISSUE THREAD

**Issue by arno974** [3liz/qgis-plugin-manager#23]
Using the upgrade command returns an error

```
qgis-plugin-manager upgrade
usage: qgis-plugin-manager [-h] [-v] {init,list,remote,update,cache,install} ...
qgis-plugin-manager: error: argument command: invalid choice: 'upgrade' (choose from 'init', 'list', 'remote', 'update', 'cache', 'install')
```

**Comment by Gustry** [comment]
As mentioned in https://github.com/3liz/qgis-atlasprint/issues/54#issuecomment-1058945738 :  
you need to upgrade your version.

`qgis-plugin-manager --version` and check with https://github.com/3liz/qgis-plugin-manager/releases

**Comment by Gustry** [comment]
Inception, to have the `upgrade` command, you need to upgrade first ;-)

**Comment by arno974** [comment]
Thanks after the update everything works as expected !
