### ISSUE TITLE
ambigous instruction

### ISSUE THREAD

**Issue by andremano** [3liz/qgis-plugin-manager#27]
In the instructions it reads: 

> To create the first sources.list in the directory with at least the default repository https://plugins.qgis.org/ :

Where should the `qgis-plugin-manager init `be executed?  Because I only have qgis-server installed, I do not have a default repository prior to running `qgis-plugin-manager init` right? I am assuming I have to run it in this directory `./qgis/plugins`
Is this correct? Thanks

**Comment by Gustry** [comment]
It was mentioned in the first example : 
https://github.com/3liz/qgis-plugin-manager#utilisation

```
cd /path/where/you/have/plugins
# usually
cd /usr/lib/qgis/plugins
```

But the last instruction depends on your OS and if you are using `QGIS_PLUGINPATH` https://docs.qgis.org/3.22/en/docs/server_manual/config.html#environment-variables

Does that help ?

**Comment by Gustry** [comment]
I have completed the readme about this server environment variable. Otherwise, you can use the default path.
I'm closing, feel free to open a question.
