### ISSUE TITLE
be less strict with case

### ISSUE THREAD

**Issue by lhirlimann** [3liz/qgis-plugin-manager#4]
qgis-plugin-manager install lizmap does not work while qgis-plugin-manager install Lizmap does. I need to read the feed on plugins.qgis.org to know that.

Could we forget case sensitivness for installs ?

**Comment by Gustry** [comment]
I don't want to silently change the case. It might be a different plugin.

I just added a similarity check in e9d3157d42089a1a0872c1c64e38584a1d6f2ffc :

```
$ qgis-plugin-manager install lizma
Plugin lizma latest not found.
Do you mean maybe 'Lizmap' ?
```
