### ISSUE TITLE
We should have a way to know if install, rm or upgrade has changed something

### ISSUE THREAD

**Issue by laurentj** [3liz/qgis-plugin-manager#43]
In the context of Ansible, we should have a way to know if we need to restart Qgis server or not, so we don't restart it if there is no change.

I suggest to create a file, for example named `RESTART_REQUIRED` into the cache directory, when qgis plugin manager has made some changes. So Ansible (or any bash script), could restart Qgis server if this file exists (and it will delete it). 
 
It requires issue #42  and #41

**Comment by Gustry** [comment]
Similar to what was done in Py-QGIS-Server with `SERVER_RESTARTMON`

From https://docs.3liz.org/py-qgis-server/configuration.html#server-restartmon

> The file to watch for restarting workers.

So I added a new environment variable `QGIS_PLUGIN_MANAGER_RESTART_FILE`. The file will be created/touched by the tool after install/upgrade/remove.

Note that #42 is not done yet, so an `upgrade` will create the file anyway for now.

https://github.com/3liz/qgis-plugin-manager#notify-upstream-if-a-restart-is-needed
Commit e86c437803f7123a4b9f58c84b16bd00de6930bb

@laurentj Feel free to reopen if needed.
