### ISSUE TITLE
Activate plug-ins on conda version of QGIS

### ISSUE THREAD

**Issue by barnabasharris** [3liz/qgis-plugin-manager#49]
After successful installation, I'm trying to activate plug-ins in a fresh, conda (actually, micromamba) installed version of QGIS.

The plug-ins dir is here:
`/home/user/mm/envs/qgis/plugins`

general QGIS folder structure is:
```
(qgis) [user@login01 qgis]$ find . -maxdepth 1
.
./mkspecs
./cmake
./ssl
./x86_64-conda-linux-gnu
./qml
./doc
./var
./plugins
./man
./libexec
./x86_64-conda_cos6-linux-gnu
./conda-meta
./pkgconfig
./phrasebooks
./docs
./compiler_compat
./qsci
./bin
./include
./fonts
./share
./etc
./sbin
./translations
./lib
```

Output from `qgis-plugin-manager list`

```
QGIS version : 3.22.11
List all plugins in /lustre/home/user/mm/envs/qgis/plugins

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  Folder ⬇  |  Name                      |  Version  |  Flags   |  QGIS min  |  QGIS max  |  Author                                                 |  Folder rights  |  Action ⚠  |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|mmqgis      |mmqgis                      |2021.9.10  |          |2.99        |3.99        |Michael Minn                                             |user : 0o755  |   |
|rvt-qgis    |Relief Visualization Toolbox|0.9.4.1    |Processing|3.0         |            |ZRC SAZU and University of Ljubljana (UL FGG), Žiga Maroh|user : 0o755  |   |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

```

Yet when I call `qgis_process list`, this plug-in is not listed in the providers.

Any way I can the plug-in to appear to qgis_process ?

**Comment by barnabasharris** [comment]
Hi thank you for the explanation but I cannot find the QGIS3.ini file - where is it located in my directory structure?

**Comment by Gustry** [comment]
https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#deploying-qgis-within-an-organization

In QGIS Desktop -> Settings -> Profile -> Open current profile folder, then it's in the `QGIS` folder for me.

**Comment by barnabasharris** [comment]
Thank you! Mine was located at:
`/home/user/.local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS.ini`

**Comment by barnabasharris** [comment]
QGIS.ini located at above location

**Comment by Gustry** [comment]
Keeping the ticket open for the readme and the idea.

**Comment by Gustry** [comment]
Yes indeed. Or use the environment variable `QGIS_PLUGINPATH`
https://github.com/3liz/qgis-plugin-manager/blob/master/README.md#utilisation

**Comment by Gustry** [comment]
I have update the readme.md with 0589423 about these notes.
