### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by SYGdev** [3liz/qgis-plugin-manager#53]
I'm facing a problem to update list qgis-plugin-manager.
The console freeze at
`Downloading https://plugins.qgis.org/plugins/plugins.xml?qgis=3.28...`

I tried to export my proxy parameters before to launch qgis-plugin-manager but without any success.

Do you have any clue, or what can I test ?

EDIT : Sorry was not a proxy problem but only permissions problem

**Comment by Gustry** [comment]
I will try to make a fix to check file permission when writing the XML file

Thanks for the feedback

**Comment by Gustry** [comment]
About write permission, it should be fixed with 144c4bd
