### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Forstrevier** [3liz/qgis-plugin-manager#56]
Hi.
Recently I get an error message when I type "qgis-plugin-manager update". Namely "Http Error: 403 Forbidden". Even if I want to download a plugin directly via wget, I get 403 Forbidden. Is my server blacklisted by qgis.org or does anyone know what the problem is and how I can fix the problem?

**Comment by Gustry** [comment]
Sorry, it's not easy to understand your issue.

> Is my server [...] ?

So you are using your own server for hosting a XML repository ?

Please share your commands if possible, your logs and the server you are using. Maybe your wget as well ?

**Comment by Forstrevier** [comment]
I run a web server with lizmap on it. and the server also has qgis-plugin-manager installed.
Recently the update doesn't work anymore. Apparently my server is being rejected by the download server. Therefore, a test I did, namely a direct wget on the plugin file, does not work. It gives the same error (403 Forbidden).

<img width="569" alt="Bildschirmfoto 2023-06-19 um 19 03 34" src="https://github.com/3liz/qgis-plugin-manager/assets/117937935/32b6e75e-64da-42c4-90a2-a9c5270a925e">

**Comment by Forstrevier** [comment]
<img width="1009" alt="Bildschirmfoto 2023-06-19 um 19 10 52" src="https://github.com/3liz/qgis-plugin-manager/assets/117937935/54e17b3d-642e-4631-b4fa-dc6115ee3040">

**Comment by Gustry** [comment]
The WGET command works perfectly for me, as expected : 

```bash
➜ wget https://plugins.qgis.org/plugins/lizmap_server/version/2.7.2/download/ -O lizmap.zip--2023-06-20 09:10:17--  https://plugins.qgis.org/plugins/lizmap_server/version/2.7.2/download/
Resolving plugins.qgis.org (plugins.qgis.org)... 188.114.96.2, 188.114.97.2, 2a06:98c1:3120::2, ...
Connecting to plugins.qgis.org (plugins.qgis.org)|188.114.96.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36362 (36K) [application/zip]
Saving to: ‘lizmap.zip’

lizmap.zip             100%[===========================>]  35,51K  --.-KB/s    in 0,008s  

2023-06-20 09:10:17 (4,20 MB/s) - ‘lizmap.zip’ saved [36362/36362]
```


Do you have a proxy or a firewall ?

Can you download, for instance your screenshot above ?

```bash
 wget https://user-images.githubusercontent.com/117937935/246892996-54e17b3d-642e-4631-b4fa-dc6115ee3040.png
```

I'm closing as not linked to QGIS-Plugin-Manager but only to your network I guess.

**Comment by Forstrevier** [comment]
> wget https://user-images.githubusercontent.com/117937935/246892996-54e17b3d-642e-4631-b4fa-dc6115ee3040.png

That worked.
But all requests to plugins.qgis.com are rejected with 403 Forbidden. 
It seems my server's IP is blacklisted by qgis.com.

**Comment by Gustry** [comment]
That's surprising.
If you think so, I would ask on QGIS dev mailing list.

In the maintime, you can use our own plugin repository : 

```bash
vim sources.list
https://packages.3liz.org/pub/server-plugins-repository/stable/plugins.[VERSION].xml
```

It should pick the correct XML on https://packages.3liz.org/pub/server-plugins-repository/stable/

**Comment by Forstrevier** [comment]
> ```shell
> https://packages.3liz.org/pub/server-plugins-repository/stable/plugins.[VERSION].xml
> ```

works perfectly, thank you.

<img width="772" alt="Bildschirmfoto 2023-06-21 um 17 22 22" src="https://github.com/3liz/qgis-plugin-manager/assets/117937935/e97a3cf0-c474-4aa2-b7b1-6df4265e763c">
