### ISSUE TITLE
User-Agent: Move from `Mozilla/5.0` to `Mozilla/5.0 QGIS/<version>/<os-info>`

### ISSUE THREAD

**Issue by benz0li** [3liz/qgis-plugin-manager#66]
Due to https://lists.osgeo.org/pipermail/qgis-user/2024-May/054439.html.

Cross references:

* https://github.com/qgis/QGIS-Django/issues/402

**Comment by benz0li** [comment]
See also https://github.com/qgis/QGIS/issues/57428.

**Comment by benz0li** [comment]
QGIS User-Agent: https://github.com/qgis/QGIS/blob/e185b6b605fc3082b6dd999278568db19c48072a/src/core/network/qgsnetworkaccessmanager.cpp#L303-L307

**Comment by benz0li** [comment]
Ping @Gustry

**Comment by Gustry** [comment]
According to QGIS Desktop, it's following this format : 

> User-Agent: Mozilla/5.0 QGIS/33406/Ubuntu 22.04.4 LTS

**Comment by Gustry** [comment]
Ah sorry, thanks for the link : 

>   userAgent += QStringLiteral( "QGIS/%1/%2" ).arg( Qgis::versionInt() ).arg( QSysInfo::prettyProductName() );
